/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export default function TermsAndConditions() {
  return (
    <div className="relative w-full pt-32 pb-16 px-6">
      <div className="max-w-3xl mx-auto bg-card border border-border-custom rounded-3xl p-8 shadow-2xl">
        <h1 className="font-display text-2xl sm:text-3xl font-black uppercase text-white mb-6 tracking-tight">
          Terms And Conditions
        </h1>
        <p className="font-sans text-xs text-text-muted mb-4 uppercase">
          Effective Date: October 1, 2025
        </p>

        <div className="font-sans text-xs sm:text-sm text-text-main leading-relaxed space-y-6">
          <p>
            Welcome to Xenishio Digital. By using this website, completing estimates, or initiating audits, you agree to comply with our commercial operating guidelines.
          </p>

          <h3 className="font-display font-bold text-xs uppercase text-white tracking-wider pt-2">
            1. Contract and Estimations
          </h3>
          <p>
            Any estimate generated by our interactive Cost Calculator is designed to serve as a preliminary budget range based on selected options. A firm commercial proposal and technical brief will be formulated and signed by both parties before work begins.
          </p>

          <h3 className="font-display font-bold text-xs uppercase text-white tracking-wider pt-2">
            2. Payment Milestones
          </h3>
          <p>
            Unless explicitly agreed otherwise, projects operate under a 50% initial retainer model. Handover and transfer of administrator credentials require full settlement of the remaining 50% final milestone balance.
          </p>

          <h3 className="font-display font-bold text-xs uppercase text-white tracking-wider pt-2">
            3. Delivery Schedulers
          </h3>
          <p>
            Turnaround targets (e.g., 3–5 days for Starter, 7–14 days for Growth) begin after the receipt of all required initial brand assets, copy briefs, and retainer deposits. Delay in asset submission will extend overall project delivery dates accordingly.
          </p>

          <h3 className="font-display font-bold text-xs uppercase text-white tracking-wider pt-2">
            4. Warranty Support
          </h3>
          <p>
            Corporate and business plans include 15–30 days of post-launch warranty support to resolve any minor bugs or visual alignment shifts. Ongoing maintenance can be secured via our monthly care plans.
          </p>
        </div>
      </div>
    </div>
  );
}
